Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2023-07, with the labels that each got.

#195 Add RBAC rules for mcad and ray roles
  config/rbac/role.yaml
  controllers/dspipeline_controller.go
Labels: approved, lgtm

#190 Add MLMD components to Network Policy
  config/internal/common/mlmd-envoy-dashboard-access-policy.yaml.tmpl
  config/internal/common/policy.yaml.tmpl
  controllers/common.go
Labels: approved, lgtm

#196 Infer the "secure" field in dspa based on scheme
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  controllers/dspipeline_params.go
  controllers/util/util.go
Labels: approved, lgtm

#205 Update dspo image to latest in params.
  config/base/params.env
Labels: lgtm

#219 change oauth proxy digest value to manifest list digest of tag v4.10
  config/base/params.env
Labels: approved, lgtm, ok-to-test

#215 Add issue forms for dspo.
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: approved, lgtm

#213 Add gh to jira action.
  .github/workflows/gh-to-jira.yaml
Labels: approved, lgtm

#224 Fix typo in pr template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#133 Add Database and ObjectStorage Health Checks
  api/v1alpha1/dspipeline_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/samples/dspa_all_fields.yaml
  config/samples/dspa_local_dev.yaml
  controllers/config/defaults.go
  controllers/database.go
  controllers/dspipeline_controller.go
  controllers/dspipeline_params.go
  controllers/metrics.go
  controllers/storage.go
  controllers/suite_test.go
  go.mod
  go.sum
Labels: approved, lgtm, qe/verify

#225 Update Makefile for power kustomize change
  Makefile
Labels: approved, lgtm, ok-to-test

#212 Add push artifact work around.
  config/internal/apiserver/artifact_script.yaml.tmpl
  controllers/testdata/declarative/case_0/expected/created/configmap_artifact_script.yaml
  controllers/testdata/declarative/case_2/expected/created/configmap_artifact_script.yaml
  controllers/testdata/declarative/case_4/expected/created/configmap_artifact_script.yaml
  controllers/testdata/declarative/case_5/expected/created/configmap_artifact_script.yaml
Labels: qe/verify

#231 Turn of auto image tagging for dspo.
  .github/workflows/tag-release-quay.yml
Labels: lgtm

#232 Use unauthenticated images for go-toolset.
  Dockerfile
Labels: approved, lgtm

#228 Add push artifact work around.
  Dockerfile
  config/internal/apiserver/artifact_script.yaml.tmpl
  controllers/testdata/declarative/case_0/expected/created/configmap_artifact_script.yaml
  controllers/testdata/declarative/case_2/expected/created/configmap_artifact_script.yaml
  controllers/testdata/declarative/case_4/expected/created/configmap_artifact_script.yaml
  controllers/testdata/declarative/case_5/expected/created/configmap_artifact_script.yaml
Labels: approved, lgtm

#234 Add workflow for src image build and push to tag.
  .github/workflows/tag-and-build.yml
Labels: lgtm

#235 Add v1.0.1 shas.
  config/base/params.env
Labels: lgtm

#236 Add v1.1.1 shas.
  config/base/params.env
Labels: approved, lgtm

#238 Tag build image exists
  .github/actions/build/action.yaml
  .github/workflows/tag-and-build.yml
Labels: lgtm
