Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2023-06, with the labels that each got.

#128 default to deploying dspo's main tag
  config/base/params.env
Labels: approved, lgtm

#130 Revert "Update DSP Operator labels"
  config/manager/manager-service.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
Labels: approved, lgtm

#132 Reorder Multi-container Deployments to use main container first
  config/internal/apiserver/deployment.yaml.tmpl
  config/internal/mlpipelines-ui/deployment.yaml.tmpl
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/mlpipelines-ui_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/mlpipelines-ui_deployment.yaml
Labels: approved, lgtm

#129 Add ML-Metadata Component
  api/v1alpha1/dspipeline_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/base/kustomization.yaml
  config/base/params.env
  config/configmaps/files/config.yaml
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/ml-metadata/metadata-envoy.configmap.yaml.tmpl
  config/internal/ml-metadata/metadata-envoy.deployment.yaml.tmpl
  config/internal/ml-metadata/metadata-envoy.service.yaml.tmpl
  config/internal/ml-metadata/metadata-grpc.deployment.yaml.tmpl
  config/internal/ml-metadata/metadata-grpc.service.yaml.tmpl
  config/internal/ml-metadata/metadata-grpc.serviceaccount.yaml.tmpl
  config/internal/ml-metadata/metadata-writer.deployment.yaml.tmpl
  config/internal/ml-metadata/metadata-writer.role.yaml.tmpl
  config/internal/ml-metadata/metadata-writer.rolebinding.yaml.tmpl
  config/internal/ml-metadata/metadata-writer.serviceaccount.yaml.tmpl
  config/internal/mlpipelines-ui/deployment.yaml.tmpl
  config/manager/manager.yaml
  controllers/config/defaults.go
  controllers/dspipeline_controller.go
  controllers/dspipeline_params.go
  controllers/mlmd.go
  controllers/testdata/declarative/case_2/expected/created/mlpipelines-ui_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/mlpipelines-ui_deployment.yaml
  kfdef/kfdef.yaml
Labels: approved, lgtm

#169 Add v0.2.2 tags.
  config/base/params.env
Labels: lgtm

#183 Give pipeline runner access to mcad/ray res.
  config/internal/apiserver/role_pipeline-runner.yaml.tmpl
Labels: lgtm

#184 Provide dspo with rbac needed to hand out mcad/ray perms.
  config/rbac/role.yaml
Labels: approved, lgtm

#171 Fix: update template name to be more unique
  controllers/config/templating.go
Labels: approved, lgtm, needs-ok-to-test

#185 Update image configs to 1.0.0
  config/base/params.env
Labels: lgtm, do-not-merge/hold

#167 Add image-check automation
  .github/workflows/image-check.yaml
  config/base/params.env
Labels: approved, lgtm
