Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2023-04, with the labels that each got.

#78 Add a data-science-pipelines-operator label for DSPO manifests
  config/manager/manager-service.yaml
  config/manager/manager.yaml
Labels: approved, lgtm

#80 Github action: Maintain consistency in var names
  .github/workflows/pr-close-image-delete.yml
  .github/workflows/tag-release-quay.yml
Labels: approved, lgtm

#82 Github action: Direct authenticate the skopeo function
  .github/workflows/pr-close-image-delete.yml
Labels: approved, lgtm

#79 Update e2e basictests to use APIServer Route
  config/internal/apiserver/role_ds-pipeline.yaml.tmpl
  tests/basictests/dsp-operator.sh
Labels: approved, lgtm

#84 GH Action: Use push event instead of pull request
  .github/workflows/pr-close-image-delete.yml
  .github/workflows/pr-merged-image-delete.yml
Labels: approved, lgtm

#87 Allow DSPA metrics to be scrapped by rho…
  config/internal/common/policy.yaml.tmpl
Labels: approved, lgtm

#37 Create DSPA Status Condition fields
  config/samples/dspa_all_fields.yaml
  controllers/config/defaults.go
  controllers/dspipeline_controller.go
  tests/basictests/dsp-operator.sh
  tests/scripts/installandtest.sh
Labels: approved, lgtm

#89 Clarify readme.
  README.md
Labels: approved, lgtm

#90 lower resource requests
  config/base/params.env
  config/manager/manager.yaml
  tests/basictests/dsp-operator.sh
Labels: approved

#88 Add/Enable Customizable Sample Pipeline to APIServer
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/deployment.yaml.tmpl
  config/internal/apiserver/sample-config.yaml.tmpl
  config/internal/apiserver/sample-pipeline.yaml.tmpl
  controllers/apiserver.go
  controllers/dspipeline_controller_test.go
  controllers/testdata/deploy/case_2/cr.yaml
  controllers/testdata/deploy/case_3/cr.yaml
  controllers/testdata/results/case_0/apiserver/deployment.yaml
  controllers/testdata/results/case_2/apiserver/deployment.yaml
  controllers/testdata/results/case_3/apiserver/sample-config.yaml
  controllers/testdata/results/case_3/apiserver/sample-pipeline.yaml
Labels: approved, lgtm

#91 Remove some conditions in DSPA
  controllers/config/defaults.go
  controllers/dspipeline_controller.go
Labels: approved, lgtm

#92 Add CR Ready Status Metrics
  README.md
  controllers/dspipeline_controller.go
  controllers/metrics.go
  go.mod
  main.go
Labels: lgtm

#93 Add namespace and DSPA name in Reconciler logs
  controllers/apiserver.go
  controllers/common.go
  controllers/database.go
  controllers/dspipeline_controller.go
  controllers/mlpipeline_ui.go
  controllers/persistence_agent.go
  controllers/scheduled_workflow.go
  controllers/storage.go
  controllers/viewer_crd.go
Labels: approved, lgtm

#98 relicense project to Apache 2.0
  LICENSE
Labels: approved, lgtm

#99 Fix: only enable tag-release-quay workflow for upstream opendatahub-io
  .github/workflows/tag-release-quay.yml
Labels: approved, lgtm, ok-to-test

#100 update sample config aws secret key values
  config/samples/dspa_all_fields.yaml
  config/samples/dspa_simple_external_storage.yaml
Labels: approved, lgtm

#95 Add tests for DSP experiments
  tests/basictests/dsp-operator.sh
Labels: approved, lgtm

#107 e2e: 5m sleep waiting for pods to come up had no effect, move it up
  tests/basictests/dsp-operator.sh
Labels: approved, lgtm

#108 Make object store port/secure scheme optional.
  README.md
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/samples/external-object-storage/dspa_simple.yaml
  config/samples/external-object-storage/kustomization.yaml
  config/samples/external-object-storage/storage-creds.yaml
  controllers/config/defaults.go
  controllers/dspipeline_params.go
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/storage_secret.yaml
Labels: approved, lgtm

#109 Fix Scheduled Workflow role to allow create runs
  config/internal/scheduled-workflow/role.yaml.tmpl
Labels: approved, lgtm
