Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2023-10, with the labels that each got.

#360 Added descriptive comments to DSPASpec
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
Labels: approved, lgtm, qe/verify

#386 Update 1.5 compatibility doc.
  docs/release/compatibility.yaml
Labels: approved, lgtm

#388 Update DSP version compatibility doc.
  docs/release/compatibility.md
Labels: approved, lgtm

#390 Release v1.5.0
  config/base/params.env
Labels: approved, lgtm, release-automation

#396 Upgrade to Go 1.19
  .github/workflows/functests.yml
  .github/workflows/precommit.yml
  .github/workflows/unittests.yml
  Dockerfile
  controllers/testutil/util.go
  go.mod
Labels: approved, lgtm

#401 Rebase from dspv1 main, Add v2undeploy command to Makefile
  .github/workflows/add-issues-to-odh-project.yml
  .github/workflows/functests.yml
  .github/workflows/precommit.yml
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
  README.md
  api/v1alpha1/dspipeline_types.go
  config/base/kustomization.yaml
  config/base/params.env
  config/configmaps/files/config.yaml
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/manager/manager.yaml
  config/v2/cache/serviceaccount.yaml
  config/v2/driver/kustomization.yaml
  config/v2/exithandler/controller/kustomization.yaml
  config/v2/exithandler/kustomization.yaml
  config/v2/exithandler/webhook/kustomization.yaml
  config/v2/kfptask/kustomization.yaml
  config/v2/kustomization.yaml
  config/v2/pipelineloop/controller/kustomization.yaml
  config/v2/pipelineloop/kustomization.yaml
  config/v2/pipelineloop/webhook/kustomization.yaml
  controllers/testutil/equalities.go
  controllers/testutil/util.go
  docs/release/compatibility.md
  docs/release/compatibility.yaml
  go.mod
  go.sum
  kfdef/kfdef.yaml
Labels: approved, lgtm

#394 Parameterize DSPO max concurrency count
  config/base/kustomization.yaml
  config/base/params.env
  config/manager/manager.yaml
  controllers/dspipeline_controller.go
  main.go
Labels: approved, lgtm

#397 Opt out as reviewers for data-science-pipeline-operator
  OWNERS
Labels: approved, lgtm

#399 Added new section for Deployment and testing guidelines for Developers
  README.md
Labels: approved, lgtm

#406 Fix Leader Election Cluster Role Names
  config/v2/exithandler/clusterrole.leaderelection.yaml
  config/v2/kfptask/clusterrole.leaderelection.yaml
  config/v2/pipelineloop/clusterrole.leaderelection.yaml
Labels: approved, lgtm

#409 Webhook RBAC and APIServer EnvVar updates
  config/internal/apiserver/default/deployment.yaml.tmpl
  config/v2/exithandler/webhook/clusterrole.clusteraccess.yaml
  config/v2/kfptask/webhook/clusterrole.clusteraccess.yaml
  config/v2/pipelineloop/webhook/clusterrole.clusteraccess.yaml
  controllers/apiserver_test.go
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
Labels: approved, lgtm

#411 Updated ubi-minimal, go-toolset, go-toolset, ubi and ose images
  Dockerfile
  kfdef/kfdef.yaml
Labels: approved, lgtm

#414 Remove SCCs from DSPv2 manifests
  config/v2/tektoncrds/scc.anyuid.yaml
  config/v2/tektoncrds/scc.privileged.yaml
Labels: approved, lgtm

#415 Add Nightly Build/Test GHAction stub
  .github/workflows/nightly_tests.yml
Labels: approved, lgtm

#413 DSPv2 NetworkPolicy changes
  config/internal/common/default/policy.yaml.tmpl
Labels: approved, lgtm

#418 add aggregate view role
  config/rbac/aggregate_dspa_role_edit.yaml
  config/rbac/aggregate_dspa_role_view.yaml
  config/rbac/kustomization.yaml
Labels: approved, lgtm

#419 Update packages
  go.mod
  go.sum
Labels: approved, lgtm

#408 Added better variable handling of DSPO deployed manifest names
  config/internal/apiserver/deployment.yaml.tmpl
  config/internal/apiserver/monitor.yaml.tmpl
  config/internal/apiserver/role_ds-pipeline-user-access.yaml.tmpl
  config/internal/apiserver/role_ds-pipeline.yaml.tmpl
  config/internal/apiserver/role_pipeline-runner.yaml.tmpl
  config/internal/apiserver/rolebinding_ds-pipeline.yaml.tmpl
  config/internal/apiserver/rolebinding_pipeline-runner.yaml.tmpl
  config/internal/apiserver/route.yaml.tmpl
  config/internal/apiserver/sa_ds-pipeline.yaml.tmpl
  config/internal/apiserver/sa_pipeline-runner.yaml.tmpl
  config/internal/apiserver/sample-config.yaml.tmpl
  config/internal/apiserver/sample-pipeline.yaml.tmpl
  config/internal/apiserver/service.yaml.tmpl
  config/internal/common/policy.yaml.tmpl
  config/internal/persistence-agent/deployment.yaml.tmpl
  config/internal/persistence-agent/role.yaml.tmpl
  config/internal/persistence-agent/rolebinding.yaml.tmpl
  config/internal/persistence-agent/sa.yaml.tmpl
  config/internal/scheduled-workflow/deployment.yaml.tmpl
  config/internal/scheduled-workflow/role.yaml.tmpl
  config/internal/scheduled-workflow/rolebinding.yaml.tmpl
  config/internal/scheduled-workflow/sa.yaml.tmpl
  controllers/apiserver.go
  controllers/apiserver_test.go
  controllers/dspipeline_controller.go
  controllers/dspipeline_params.go
  controllers/persistence_agent.go
  controllers/persistence_agent_test.go
  controllers/scheduled_workflow.go
  controllers/scheduled_workflow_test.go
Labels: approved, lgtm

#422 Last changes for DSPv2 PoC
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  config/internal/common/default/policy.yaml.tmpl
  config/v2/driver/deployment.yaml
  config/v2/exithandler/clusterrole.leaderelection.yaml
  config/v2/pipelineloop/controller/deployment.yaml
  config/v2/pipelineloop/webhook/deployment.yaml
  config/v2/tektoncrds/kustomization.yaml
  controllers/dspipeline_params.go
  controllers/mlmd.go
  controllers/mlmd_test.go
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
Labels: approved, lgtm

#430 Update Metrics publish to accept a boundless number of conditions to publish
  controllers/dspipeline_controller.go
Labels: approved, lgtm

#435 Release v1.6.0
  config/base/params.env
Labels: release-automation
