Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2023-08, with the labels that each got.

#223 Added RequeueAfter to ensure periodic reconciliation
  controllers/dspipeline_controller.go
Labels: approved, lgtm, qe/verify

#243 Fix actions
  .github/actions/build/action.yaml
  .github/workflows/build-main.yml
  .github/workflows/build-prs.yml
  .github/workflows/build-tags.yml
  .github/workflows/image-check.yaml
  .github/workflows/pr-merged-image-delete.yml
  .github/workflows/precommit.yml
  .github/workflows/tag-release-quay.yml
Labels: approved, lgtm

#249 Add secure pr build triggers.
  .github/workflows/build-prs-trigger.yaml
  .github/workflows/build-prs.yml
Labels: lgtm

#245 Add non-default SAs to MariaDB and Minio
  config/internal/mariadb/deployment.yaml.tmpl
  config/internal/mariadb/mariadb-sa.yaml.tmpl
  config/internal/minio/deployment.yaml.tmpl
  config/internal/minio/minio-sa.yaml.tmpl
  controllers/database.go
  controllers/storage.go
Labels: approved, lgtm, qe/verify

#252 Update params.env to latest dsp images.
  config/base/params.env
Labels: lgtm, do-not-merge/hold

#254 Add v1.2.0 shas.
  config/base/params.env
Labels: lgtm

#255 Allow odh sync to fork from user fork.
  .github/workflows/odh-manifests-PR-sync.yml
Labels: lgtm

#259 Add branch inputs and fix repo name in PR sync GH workflow
  .github/workflows/odh-manifests-PR-sync.yml
Labels: approved, lgtm

#261 Fixing GH workflow repo name and updating input descriptions
  .github/workflows/odh-manifests-PR-sync.yml
Labels: lgtm

#264 Correct remote location for manifest sync action.
  .github/workflows/odh-manifests-PR-sync.yml
Labels: lgtm

#266 Add DharmitD to DSPO approvers
  OWNERS
Labels: approved, lgtm

#267 Release docs
  .github/workflows/image-check.yaml
  .gitignore
  config/base/params.env
  docs/release/compatibility.md
  docs/release/compatibility.yaml
  docs/release/release_workflow.md
  scripts/release/README.md
  scripts/release/params.py
  scripts/release/release.py
  scripts/release/template/version_doc.md
  scripts/release/version_doc.py
Labels: approved, lgtm

#272 Run PR builds on only code changes...
  .github/workflows/build-prs-trigger.yaml
  .github/workflows/build-prs.yml
Labels: approved, lgtm

#276 Fixed "Installation" link
  README.md
Labels: approved, lgtm

#277 Correct gh pr trigger inputs.
  .github/workflows/build-prs.yml
Labels: approved, lgtm

#265 Update ObjectStore HealthCheck to use StatObject
  controllers/storage.go
  controllers/suite_test.go
Labels: approved, lgtm, qe/verify

#283 Automated release
  .github/scripts/release_create/create_tag_release.sh
  .github/scripts/release_create/notify.sh
  .github/scripts/release_create/validate_pr.sh
  .github/scripts/release_create/vars.sh
  .github/scripts/release_prep/create_branches.sh
  .github/scripts/release_prep/generate_pr.sh
  .github/scripts/release_prep/prereqs.sh
  .github/scripts/release_prep/templates/config.yaml
  .github/scripts/release_trigger/upload-data.sh
  .github/scripts/tests/tests.sh
  .github/workflows/build-tags.yml
  .github/workflows/odh-manifests-PR-sync.yml
  .github/workflows/precommit.yml
  .github/workflows/release_create.yaml
  .github/workflows/release_prep.yaml
  .github/workflows/release_tests.yaml
  .github/workflows/release_trigger.yaml
  OWNERS
  docs/release/compatibility.md
  docs/release/compatibility.yaml
  scripts/release/params.py
  scripts/release/version_doc.py
Labels: approved, lgtm

#278 Add Unit Tests
  Makefile
  controllers/apiserver_test.go
  controllers/common_test.go
  controllers/database_test.go
  controllers/dspipeline_controller_func_test.go
  controllers/dspipeline_fake_controller.go
  controllers/dspipeline_params.go
  controllers/mlmd_test.go
  controllers/mlpipeline_ui_test.go
  controllers/persistence_agent_test.go
  controllers/scheduled_workflow_test.go
  controllers/storage_test.go
  controllers/suite_test.go
  controllers/testutil/util.go
  go.mod
Labels: approved, lgtm

#290 Update DSP version compatibility doc.
  docs/release/compatibility.md
Labels: approved, lgtm

#291 Release v1.3.0
  config/base/params.env
Labels: approved, lgtm, release-automation

#292 Correct org mention in release notes links.
  .github/workflows/release_create.yaml
Labels: approved, lgtm

#295 Hardcode obj store info in artifact script.
  config/internal/apiserver/artifact_script.yaml.tmpl
Labels: approved, lgtm, qe/verify

#306 Correct artifact endpoints/bucket for test cases.
  controllers/testdata/declarative/case_0/expected/created/configmap_artifact_script.yaml
  controllers/testdata/declarative/case_2/expected/created/configmap_artifact_script.yaml
  controllers/testdata/declarative/case_4/expected/created/configmap_artifact_script.yaml
  controllers/testdata/declarative/case_5/expected/created/configmap_artifact_script.yaml
Labels: lgtm
