Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2023-03, with the labels that each got.

#28 Remove owner.
  OWNERS
Labels: approved, lgtm

#26 Updates to have auth permission for oauth proxy
  config/internal/mlpipelines-ui/deployment.yaml.tmpl
  config/internal/mlpipelines-ui/role.yaml.tmpl
  controllers/testdata/results/case_0/mlpipelines-ui/deployment.yaml
  controllers/testdata/results/case_2/mlpipelines-ui/deployment.yaml
Labels: approved, lgtm

#33 add shortName for datasciencepipelinesapplications
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
Labels: approved, lgtm

#36 add vscode to .gitignore
  .gitignore
Labels: approved, lgtm

#31 Parameterize images
  config/base/kustomization.yaml
  config/configmaps/files/config.yaml
  config/configmaps/kustomization.yaml
  config/manager/manager.yaml
  controllers/config/defaults.go
  controllers/dspipeline_controller_test.go
  controllers/dspipeline_params.go
  controllers/testdata/deploy/case_0/config.yaml
  controllers/testdata/deploy/case_1/config.yaml
  controllers/testdata/deploy/case_2/config.yaml
  controllers/testdata/deploy/case_3/config.yaml
  go.mod
  go.sum
  main.go
Labels: approved, lgtm

#32 Replace busybox img
  config/configmaps/files/config.yaml
  config/manager/manager.yaml
  controllers/testdata/deploy/case_0/config.yaml
  controllers/testdata/deploy/case_1/config.yaml
  controllers/testdata/deploy/case_2/config.yaml
  controllers/testdata/deploy/case_2/cr.yaml
  controllers/testdata/deploy/case_3/config.yaml
  controllers/testdata/deploy/case_3/cr.yaml
  controllers/testdata/results/case_0/apiserver/deployment.yaml
  controllers/testdata/results/case_0/mariadb/deployment.yaml
  controllers/testdata/results/case_0/minio/deployment.yaml
  controllers/testdata/results/case_0/mlpipelines-ui/deployment.yaml
  controllers/testdata/results/case_0/persistence-agent/deployment.yaml
  controllers/testdata/results/case_0/scheduled-workflow/deployment.yaml
  controllers/testdata/results/case_0/viewer-crd/deployment.yaml
  controllers/testdata/results/case_2/apiserver/deployment.yaml
  controllers/testdata/results/case_2/mariadb/deployment.yaml
  controllers/testdata/results/case_2/minio/deployment.yaml
  controllers/testdata/results/case_2/mlpipelines-ui/deployment.yaml
  controllers/testdata/results/case_2/persistence-agent/deployment.yaml
  controllers/testdata/results/case_2/scheduled-workflow/deployment.yaml
  controllers/testdata/results/case_2/viewer-crd/deployment.yaml
  controllers/testdata/results/case_3/apiserver/deployment.yaml
Labels: approved, lgtm

#38 Add kfdef image parameters.
  config/base/kustomization.yaml
  config/base/params.env
  config/base/params.yaml
  config/configmaps/files/config.yaml
  config/manager/manager.yaml
Labels: lgtm

#40 Add target ns to make deploy/undeploy.
  Makefile
  README.md
  config/base/kustomization.yaml
Labels: approved, lgtm

#34 Add enable route functionality.
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/deployment.yaml.tmpl
  config/internal/apiserver/route.yaml.tmpl
  config/internal/apiserver/sa_ds-pipeline.yaml.tmpl
  config/internal/apiserver/service.yaml.tmpl
  config/internal/common/clusterrolebinding.yaml.tmpl
  config/internal/common/policy.yaml.tmpl
  config/rbac/role.yaml
  controllers/apiserver.go
  controllers/common.go
  controllers/dspipeline_controller.go
  controllers/mlpipeline_ui.go
  controllers/testdata/deploy/case_2/cr.yaml
  controllers/testdata/results/case_0/apiserver/deployment.yaml
  controllers/testdata/results/case_2/apiserver/deployment.yaml
  controllers/testdata/results/case_3/apiserver/deployment.yaml
Labels: approved, lgtm

#42 Make ui/minio images required, and remove defaults.
  README.md
  api/v1alpha1/dspipeline_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/base/kustomization.yaml
  config/base/params.env
  config/configmaps/files/config.yaml
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/manager/manager.yaml
  config/samples/dspa_simple.yaml
  config/samples/dspa_simple_external_storage.yaml
  controllers/config/defaults.go
  controllers/dspipeline_controller.go
  controllers/dspipeline_controller_test.go
  controllers/dspipeline_params.go
  controllers/mlpipeline_ui.go
  controllers/testdata/deploy/case_0/cr.yaml
  controllers/testdata/deploy/case_1/config.yaml
  controllers/testdata/deploy/case_1/cr.yaml
  controllers/testdata/deploy/case_2/config.yaml
  controllers/testdata/deploy/case_3/config.yaml
  controllers/testdata/results/case_0/minio/deployment.yaml
  controllers/testdata/results/case_0/mlpipelines-ui/deployment.yaml
Labels: lgtm

#43 Add required fields to e2e cr.
  tests/basictests/dsp-operator.sh
  tests/resources/dsp-operator/test-dspo-cr.yaml
Labels: lgtm

#45 Add debug sleep cmd for e2e.
  tests/basictests/dsp-operator.sh
Labels: lgtm

#44 use longhand kubebuilder optional validation markers
  api/v1alpha1/dspipeline_types.go
Labels: approved, lgtm

#52 Add debug sleep statement for ci testing.
  tests/basictests/dsp-operator.sh
Labels: approved

#54 add user to owners.
  OWNERS
Labels: lgtm

#55 Check for ready status for dspa api server pod.
  tests/basictests/dsp-operator.sh
Labels: approved, lgtm

#58 Remove the debug statements for e2e tests
  tests/basictests/dsp-operator.sh
Labels: approved, lgtm

#59 Remove ns from sample deployment to make readme work.
  config/samples/dspa_simple.yaml
Labels: lgtm

#51 Correct secret generation for external secrets.
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  controllers/config/defaults.go
  controllers/database.go
  controllers/dspipeline_controller.go
  controllers/dspipeline_controller_test.go
  controllers/dspipeline_params.go
  controllers/storage.go
  controllers/testdata/deploy/case_3/cr.yaml
  controllers/testdata/deploy/case_3/secret1.yaml
  controllers/testdata/deploy/case_3/secret2.yaml
  controllers/testdata/results/case_0/apiserver/deployment.yaml
  controllers/testdata/results/case_0/mariadb/deployment.yaml
  controllers/testdata/results/case_2/apiserver/deployment.yaml
  controllers/testdata/results/case_2/mariadb/deployment.yaml
  controllers/testdata/results/case_3/apiserver/deployment.yaml
  controllers/testdata/results/case_3/database/secret.yaml
  controllers/testdata/results/case_3/storage/secret.yaml
  controllers/testutil/util.go
Labels: lgtm

#60 Add ability to parmaterize dspo image via kfdef.
  Makefile
  config/base/kustomization.yaml
  config/base/params.env
  config/base/params.yaml
  config/manager/manager.yaml
  config/overlays/make-deploy/img_patch.yaml
  config/overlays/make-deploy/kustomization.yaml
Labels: lgtm

#61 Patch pull request image for e2e tests
  tests/scripts/install.sh
  tests/setup/kfctl_openshift.yaml
Labels: approved, lgtm

#62 Include as an approver for dspo
  OWNERS
Labels: approved, lgtm

#64 Fix the sed termination for patch of images
  tests/scripts/install.sh
Labels: approved, lgtm

#63 Match the change with odh-manifests tests for consistency
  tests/basictests/dsp-operator.sh
Labels: approved, lgtm

#66 Fix commented-out command in Makefile deploy func
  Makefile
Labels: approved, lgtm

#47 add kubebuilder validation markers for DSPA
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
Labels: approved, lgtm

#68 Adding a DSPA ServiceMonitor template
  config/crd/external/monitoring.coreos.com_servicemonitors.yaml
  config/internal/apiserver/monitor.yaml.tmpl
  config/internal/common/policy.yaml.tmpl
  config/rbac/role.yaml
  controllers/apiserver.go
  controllers/dspipeline_controller.go
Labels: approved, lgtm

#72 Allow admin/edit roles to crud dspa.
  config/rbac/aggregate_dspa_role.yaml
  config/rbac/kustomization.yaml
Labels: approved, lgtm

#73 Remove redundant/unused code.
  controllers/dspipeline_controller.go
Labels: approved, lgtm

#75 Make sure user has same access via cli and UI
  config/internal/mlpipelines-ui/deployment.yaml.tmpl
  controllers/testdata/results/case_2/mlpipelines-ui/deployment.yaml
Labels: approved, lgtm

#76 Rename the component to respect name-prefix
  config/manager/manager-service.yaml
  config/prometheus/monitor.yaml
Labels: approved, lgtm

#77 Up dspo memory to handle more users.
  config/manager/manager.yaml
Labels: approved, lgtm
