Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2024-10, with the labels that each got.

#713 Replace boto3 with numpy
  .github/scripts/python_package_upload/Dockerfile
  .github/scripts/python_package_upload/package_upload.sh
  .github/scripts/python_package_upload/package_upload_run.sh
  .github/scripts/tests/tests.sh
  .gitignore
  tests/resources/test-pipeline-run.yaml
  tests/resources/test-pipeline-with-custom-pip-server-run.yaml
  tests/resources/test-pipeline-with-custom-pip-server.py
  tests/resources/test-pipeline.py
Labels: approved, lgtm

#711 Add support for using route or service as target endpoints in the test suite
  .github/scripts/tests/tests.sh
  tests/dspa_v2_test.go
  tests/experiments_test.go
  tests/pipeline_runs_test.go
  tests/pipeline_test.go
  tests/resources/dspa-external.yaml
  tests/resources/dspa.yaml
  tests/suite_test.go
  tests/util/rest.go
Labels: approved, lgtm

#684 Accomodate changes for KFP 2.2 upgrade
  config/argo/clusterrole.argo-aggregate-to-admin.yaml
  config/argo/clusterrole.argo-aggregate-to-edit.yaml
  config/argo/clusterrole.argo-aggregate-to-view.yaml
  config/argo/clusterrole.argo-cluster-role.yaml
  config/argo/crd.workflowartifactgctasks.yaml
  config/argo/crd.workflows.yaml
  config/argo/crd.workflowtaskresult.yaml
  config/argo/deployment.workflow-controller.yaml
  config/argo/kustomization.yaml
  config/argo/role.argo.yaml
  config/base/params.env
  config/internal/apiserver/default/kfp_launcher_config.yaml.tmpl
  config/internal/workflow-controller/configmap.yaml.tmpl
  config/internal/workflow-controller/role.yaml.tmpl
  config/rbac/argo_role.yaml
  config/rbac/role.yaml
  config/samples/v2/custom-workflow-controller-config/custom-workflow-controller-configmap.yaml
  controllers/dspipeline_controller.go
Labels: lgtm

#715 Added secrets::list permissions to pipeline runner
  config/internal/apiserver/default/role_pipeline-runner.yaml.tmpl
Labels: approved, lgtm

#717 chore: Fix typos and improve grammar of README.md
  README.md
Labels: approved, lgtm

#718 Upgrade Argo images to v3.4.17
  config/base/params.env
Labels: approved, lgtm

#719 fix: add NetworkPolicy for DSP apiserver pod self traffic
  config/internal/common/argo/policy.yaml.tmpl
Labels: lgtm

#721 Release v2.7.0
  config/base/params.env
Labels: approved, lgtm, release-automation

#724 Revert "Generate params for 2.7"
  config/base/params.env
Labels: approved, lgtm

#727 switch dspa resource not found err to debug
  controllers/dspipeline_controller.go
Labels: approved, lgtm

#729 prevent dspa status update on a terminating dspa
  controllers/dspipeline_controller.go
Labels: lgtm

#730 correct pa config path
  README.md
  config/configmaps/files/config.yaml
  controllers/config/defaults.go
  controllers/testdata/README.md
  controllers/testdata/declarative/case_0/config.yaml
  controllers/testdata/declarative/case_1/config.yaml
  controllers/testdata/declarative/case_2/config.yaml
  controllers/testdata/declarative/case_3/config.yaml
  controllers/testdata/declarative/case_4/config.yaml
  controllers/testdata/declarative/case_5/config.yaml
  controllers/testdata/declarative/case_6/config.yaml
  tests/dspa_v2_test.go
Labels: approved

#732 Release v2.8.0
  config/base/params.env
Labels: lgtm, release-automation

#733 Update oauth-proxy version in compatiblity table for 2.8
  docs/release/compatibility.md
  docs/release/compatibility.yaml
Labels: approved, lgtm
