Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2024-01, with the labels that each got.

#529 Update DSP API Server cABundle error msg
  controllers/storage.go
Labels: approved, lgtm

#530 Remove mcad.ibm.com APIGroup
  config/internal/apiserver/role_pipeline-runner.yaml.tmpl
  config/rbac/role.yaml
  controllers/dspipeline_controller.go
Labels: approved, lgtm

#384 Integration Test suite + kind workflow to add them to ci
  .github/resources/crds/servicemonitor-crd.yaml
  .github/resources/dspa-lite/dspa.yaml
  .github/resources/tekton-lite/anyuid-scc.yaml
  .github/resources/tekton-lite/kustomization.yaml
  .github/resources/tekton-lite/patches/deployment_tekton-pipelines-controller.yaml
  .github/resources/tekton-lite/patches/deployment_tekton-pipelines-remote-resolvers.yaml
  .github/resources/tekton-lite/patches/deployment_tekton-pipelines-webhook.yaml
  .github/resources/tekton-lite/patches/horizontalpodautoscaler_tekton-pipelines-webhook.yaml
  .github/workflows/kind-integration.yml
  Makefile
  config/crd/external/monitoring.coreos.com_servicemonitors.yaml
  config/crd/external/route.openshift.io_routes.yaml
  config/manager/manager.yaml
  config/overlays/kind-tests/img_patch.yaml
  config/overlays/kind-tests/kustomization.yaml
  config/overlays/kind-tests/res_patch.yaml
  config/overlays/kind-tests/user_patch.yaml
  go.mod
  go.sum
  tests/Dockerfile
  tests/Makefile
  tests/Pipfile
  tests/Pipfile.lock
  tests/README.md
  tests/TESTING.md
  tests/basictests/dsp-operator.sh
  tests/dspa_test.go
  tests/experiments_test.go
  tests/main.go
  tests/pipeline_test.go
  tests/resources/dsp-operator/enable-uwm.yaml
  tests/resources/dsp-operator/test-dspo-cr.yaml
  tests/resources/dspa-lite.yaml
  tests/resources/test-pipeline-run.yaml
  tests/scripts/install.sh
  tests/scripts/installandtest.sh
  tests/setup/operatorsetup
  tests/suite_test.go
  tests/util
  tests/util/resources.go
  tests/util/rest.go
Labels: approved, lgtm

#521 Dspv2 merge - Sprint 9 Check-in Merge 2
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/resources/datasciencecluster/datasciencecluster.yaml
  .github/resources/kfdef/kfdef.yaml
  .github/workflows/upgrade-test.yml
  Makefile
  OWNERS
  README.md
  api/v1alpha1/dspipeline_types.go
  config/base/kustomization.yaml
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/default/service.yaml.tmpl
  config/internal/apiserver/sample-pipeline.yaml.tmpl
  config/internal/apiserver/sample-pipeline/sample-pipeline.yaml.tmpl
  config/internal/mariadb/default/pvc.yaml.tmpl
  config/internal/minio/default/pvc.yaml.tmpl
  config/overlays/make-deploy/img_patch.yaml
  config/overlays/make-deploy/kustomization.yaml
  config/samples/custom-configs/dspa.yaml
  controllers/database.go
  controllers/dspipeline_controller.go
  controllers/storage.go
  controllers/storage_test.go
  controllers/suite_test.go
  controllers/testdata/declarative/case_2/expected/created/sample-pipeline.yaml.tmpl
  controllers/testutil/equalities.go
  datasciencecluster/README.md
  datasciencecluster/datasciencecluster.yaml
  docs/example_pipelines/condition.yaml
  tests/Dockerfile
  tests/Makefile
  tests/README.md
  tests/scripts/install.sh
  tests/scripts/installandtest.sh
  tests/setup/datasciencecluster_openshift.yaml
  tests/setup/kfctl_openshift.yaml
Labels: approved, lgtm

#535 Dspv2 merge
  .github/resources/crds/servicemonitor-crd.yaml
  .github/resources/dspa-lite/dspa.yaml
  .github/resources/tekton-lite/anyuid-scc.yaml
  .github/resources/tekton-lite/kustomization.yaml
  .github/resources/tekton-lite/patches/deployment_tekton-pipelines-controller.yaml
  .github/resources/tekton-lite/patches/deployment_tekton-pipelines-remote-resolvers.yaml
  .github/resources/tekton-lite/patches/deployment_tekton-pipelines-webhook.yaml
  .github/resources/tekton-lite/patches/horizontalpodautoscaler_tekton-pipelines-webhook.yaml
  .github/workflows/kind-integration.yml
  Makefile
  README.md
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/crd/external/monitoring.coreos.com_servicemonitors.yaml
  config/crd/external/route.openshift.io_routes.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  config/internal/apiserver/default/role_pipeline-runner.yaml.tmpl
  config/manager/manager.yaml
  config/overlays/kind-tests/img_patch.yaml
  config/overlays/kind-tests/kustomization.yaml
  config/overlays/kind-tests/res_patch.yaml
  config/overlays/kind-tests/user_patch.yaml
  config/rbac/role.yaml
  controllers/dspipeline_controller.go
  controllers/dspipeline_params.go
  controllers/mlmd.go
  controllers/storage.go
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  go.mod
  go.sum
  tests/Dockerfile
  tests/Makefile
  tests/Pipfile
  tests/Pipfile.lock
  tests/README.md
  tests/TESTING.md
  tests/basictests/dsp-operator.sh
  tests/dspa_test.go
  tests/experiments_test.go
  tests/main.go
  tests/pipeline_test.go
  tests/resources/dsp-operator/enable-uwm.yaml
  tests/resources/dsp-operator/test-dspo-cr.yaml
  tests/resources/dspa-lite.yaml
  tests/resources/test-pipeline-run.yaml
  tests/scripts/install.sh
  tests/scripts/installandtest.sh
  tests/setup/operatorsetup
  tests/suite_test.go
  tests/util
  tests/util/resources.go
  tests/util/rest.go
Labels: lgtm

#536 Document supported Argo versions for v2
  docs/release/compatibility.yaml
Labels: approved, lgtm

#543 RHOAIENG-1724-Add V2_LAUNCHER_IMAGE and V2_DRIVER_IMAGE for dspa api server
  api/v1alpha1/dspipeline_types.go
  config/base/kustomization.yaml
  config/base/params.env
  config/configmaps/files/config.yaml
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  config/manager/manager.yaml
  config/samples/dspa_simple_v2.yaml
  controllers/config/defaults.go
  controllers/dspipeline_params.go
  controllers/testdata/declarative/case_0/deploy/cr.yaml
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/deploy/cr.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/deploy/02_cr.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/deploy/00_cr.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/deploy/cr.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_6/deploy/01_cr.yaml
  controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_7/deploy/cr.yaml
  controllers/testdata/declarative/case_7/expected/created/apiserver_deployment.yaml
  kfdef/kfdef.yaml
Labels: approved, lgtm

#544 Fix namespace reference in Integration Test docs
  tests/README.md
Labels: approved, lgtm

#546 add v2 image sources and update paths.
  .github/workflows/build-tags.yml
Labels: approved, lgtm

#545 add kfp-launcher config support.
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  config/internal/apiserver/default/kfp_launcher_config.yaml.tmpl
  config/samples/external-object-storage/dspa.yaml
  controllers/dspipeline_params.go
Labels: lgtm

#555 remove workflowcontroller from simple dspa v2.
  config/samples/dspa_simple_v2.yaml
Labels: approved, lgtm

#560 Fix go.opentelemetry.io/contrib CVE
  .github/workflows/build-prs-trigger.yaml
  .github/workflows/kind-integration.yml
  go.mod
Labels: approved
