Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2024-11, with the labels that each got.

#737 Added retry for integration test
  tests/dspa_v2_test.go
Labels: approved, lgtm

#736 Use DSPA custom ca cert on MLMD and Persistence Agent clients
  config/internal/persistence-agent/deployment.yaml.tmpl
Labels: do-not-merge/hold

#738 update apiversion for test dspas
  tests/resources/dspa-external.yaml
  tests/resources/dspa.yaml
Labels: lgtm

#734 Rename package_upload.sh to package_download.sh
  .github/scripts/python_package_upload/Dockerfile
  .github/scripts/python_package_upload/package_download.sh
Labels: approved, lgtm

#700 Improve documentation for tLSClientConfig
  controllers/database.go
Labels: approved, lgtm

#745 Bump DSPO test suite to KFP 2.10.0
  tests/dspa_v2_test.go
  tests/resources/test-pipeline-run.yaml
  tests/resources/test-pipeline-with-custom-pip-server-run.yaml
Labels: approved, lgtm

#750 Removed comment from MLMD gRPC server config
  config/internal/ml-metadata/metadata-grpc-tls-config-secret.yaml.tmpl
Labels: lgtm

#747 Added logs and event collection on integration test failures
  .github/scripts/tests/collect_logs.sh
  .github/workflows/kind-integration.yml
Labels: approved, lgtm

#744 How run the test suite locally
  .github/scripts/tests/README.md
Labels: approved, lgtm

#743 Print if REGISTRY_ADDRESS is not defined
  .github/scripts/tests/tests.sh
Labels: approved, lgtm

#756 Bump k8s version to 1.30
  .github/actions/kind/action.yml
  .github/workflows/kind-integration.yml
Labels: lgtm
