Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2024-03, with the labels that each got.

#586 Images upgraded to v1.6.3
  config/base/params.env
Labels: approved, lgtm

#588 chore: fix serving cert annotations
  config/internal/apiserver/default/service.yaml.tmpl
  config/internal/mlpipelines-ui/service.yaml.tmpl
Labels: approved, lgtm

#590 chore: remove unneeded image paths in source build wf
  .github/workflows/build-tags.yml
Labels: approved, lgtm

#585 Fixed the custom-configs sample to not require a secret named mlpipeline-minio-artifact
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/samples/v1/custom-configs/dspa.yaml
  config/samples/v1/custom-configs/kustomization.yaml
  config/samples/v1/custom-configs/mlpipeline-minio-artifact.yaml
  config/samples/v2/custom-configs/dspa.yaml
  config/samples/v2/custom-configs/storage-creds.yaml
  controllers/dspipeline_params.go
  controllers/testdata/declarative/case_7/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_7/expected/created/minio_deployment.yaml
  controllers/testdata/declarative/case_7/expected/created/mlpipelines-ui_deployment.yaml
Labels: approved, lgtm

#587 feat: Removed traces of argo server from default deployment.
  .github/resources/argo-lite/kustomization.yaml
  .github/resources/argo-lite/patch/argo_server_deployment.yaml
  .github/workflows/kind-integration.yml
  config/argo/clusterrole.argo-server-cluster-role.yaml
  config/argo/clusterrolebinding.argo-server-binding.yaml
  config/argo/deployment.argo-server.yaml
  config/argo/kustomization.yaml
  config/argo/service.argo-server.yaml
  config/argo/serviceaccount.argo-server.yaml
  config/base/params.env
  config/overlays/make-argodeploy/argo-server-image-patch.yaml
  config/overlays/make-argodeploy/kustomization.yaml
  config/overlays/odh/kustomization.yaml
Labels: approved, lgtm

#597 chore: allow make deploy to fully deploy v2 stack
  .github/resources/argo-lite/kustomization.yaml
  Makefile
  README.md
  config/overlays/make-argodeploy/kustomization.yaml
  config/overlays/make-deploy/img_patch.yaml
  config/overlays/make-deploy/kustomization.yaml
Labels: lgtm

#596 Upgrade envoy proxy image and configuration
  config/base/params.env
  config/internal/ml-metadata/metadata-envoy.configmap.yaml.tmpl
  config/internal/ml-metadata/metadata-envoy.deployment.yaml.tmpl
  controllers/testdata/declarative/case_5/expected/created/metadata-envoy_deployment.yaml
Labels: approved, lgtm

#599 Disable samples by default
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  controllers/testdata/declarative/case_0/deploy/cr.yaml
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_7/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_8/expected/created/apiserver_deployment.yaml
Labels: lgtm

#601 Set MariaDB and Envoy Proxy with their sha digests
  config/base/params.env
Labels: approved, lgtm

#602 chore: remove argo server from rhoai overlay
  config/overlays/rhoai/kustomization.yaml
Labels: lgtm

#598 Added the additional permissions in the pipeline runner file for Ray
  config/internal/apiserver/default/role_pipeline-runner.yaml.tmpl
  config/rbac/role.yaml
  controllers/dspipeline_controller.go
Labels: approved, lgtm

#603 chore: use pipelines default pipeline store path
  config/internal/apiserver/default/server-config.yaml.tmpl
  controllers/testdata/declarative/case_0/expected/created/configmap_server_config.yaml
  controllers/testdata/declarative/case_6/expected/created/configmap_server_config.yaml
Labels: lgtm

#605 feat: always enable server config and make it customizable
  api/v1alpha1/dspipeline_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  config/internal/apiserver/default/server-config.yaml.tmpl
  controllers/config/defaults.go
  controllers/dspipeline_params.go
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_0/expected/created/configmap_server_config.yaml
  controllers/testdata/declarative/case_2/deploy/cr.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_6/expected/created/configmap_server_config.yaml
  controllers/testdata/declarative/case_7/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_8/expected/created/apiserver_deployment.yaml
Labels: approved, lgtm

#609 fix: fail templating gracefully
  controllers/config/manifest.go
  controllers/config/templating.go
Labels: lgtm

#611 Simplify sample pipeline input parameters
  config/internal/apiserver/sample-pipeline/sample-pipeline.yaml.tmpl
  controllers/testdata/declarative/case_7/expected/created/sample-pipeline.yaml.tmpl
  docs/example_pipelines/iris/iris-pipeline.py
  docs/example_pipelines/iris/iris-pipeline.yaml
Labels: approved, lgtm

#610 chore: clean up unused artifacts, add deprecated notices.
  .golangci.yaml
  api/v1alpha1/dspipeline_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/base/kustomization.yaml
  config/base/params.env
  config/configmaps/files/config.yaml
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/crdviewer/deployment.yaml.tmpl
  config/internal/crdviewer/role.yaml.tmpl
  config/internal/crdviewer/rolebinding.yaml.tmpl
  config/internal/crdviewer/serviceaccount.yaml.tmpl
  config/manager/manager.yaml
  config/samples/v2/dspa-all-fields/dspa_all_fields.yaml
  controllers/crdviewer.go
  controllers/crdviewer_test.go
  controllers/dspipeline_controller.go
  controllers/dspipeline_params.go
  controllers/mlmd_test.go
  controllers/workflow_controller_test.go
Labels: approved, lgtm

#589 Refactor integration test suite to use testify
  Makefile
  tests/README.md
  tests/dspa_v2_test.go
  tests/experiments_test.go
  tests/pipeline_test.go
  tests/suite_test.go
  tests/util/resources.go
  tests/util/rest.go
Labels: approved, lgtm, do-not-merge/hold

#615 Add integration tests for external storage/db connections
  .github/resources/mariadb/deployment.yaml
  .github/resources/mariadb/kustomization.yaml
  .github/resources/mariadb/pvc.yaml
  .github/resources/mariadb/secret.yaml
  .github/resources/mariadb/service.yaml
  .github/resources/minio/deployment.yaml
  .github/resources/minio/kustomization.yaml
  .github/resources/minio/pvc.yaml
  .github/resources/minio/secret.yaml
  .github/resources/minio/service.yaml
  .github/workflows/kind-integration.yml
  tests/dspa_v2_test.go
  tests/resources/dspa-external-lite.yaml
Labels: approved, lgtm

#614 Add System Certs when they are not available or overridden
  .github/workflows/functests.yml
  .pre-commit-config.yaml
  controllers/config/defaults.go
  controllers/dspipeline_params.go
  controllers/testdata/declarative/case_8/deploy/00_configmap.yaml
  controllers/testdata/declarative/case_8/expected/created/configmap_dspa_trusted_ca.yaml
  controllers/testdata/tls/ca-bundle.crt
  controllers/util/util.go
Labels: lgtm

#616 Add params unittest cases for cabundle
  .pre-commit-config.yaml
  Makefile
  controllers/dspipeline_fake_controller.go
  controllers/dspipeline_params.go
  controllers/dspipeline_params_test.go
  controllers/testdata/tls/dummy-ca-bundle.crt
  controllers/testdata/tls/empty-ca-bundle.crt
  controllers/testutil/util.go
Labels: lgtm

#617 chore: add ssl env to functest
  Makefile
Labels: lgtm

#618 Remove unnecessary DSPO parameters
  config/base/kustomization.yaml
  config/base/params.env
  config/manager/manager.yaml
Labels: approved, lgtm
