Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2024-08, with the labels that each got.

#679 Consolidate kustomize binaries in DSPO Makefile
  .github/workflows/kind-integration.yml
  Makefile
Labels: approved, lgtm

#681 add ability to customize `kfp-launcher` ConfigMap data contents
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/default/kfp_launcher_config.yaml.tmpl
  config/samples/v2/dspa-all-fields/dspa_all_fields.yaml
  controllers/dspipeline_params.go
  controllers/dspipeline_params_test.go
  controllers/testutil/util.go
Labels: approved, lgtm

#682 Clarify the "DSPA not found" log message that happens when a DSPA is deleted
  controllers/dspipeline_controller.go
Labels: approved, lgtm

#669 Expose API Server and Envoy endpoints and add a new Envoy condition
  api/v1alpha1/dspipeline_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/ml-metadata/metadata-envoy.deployment.yaml.tmpl
  config/samples/v2/dspa-all-fields/dspa_all_fields.yaml
  controllers/apiserver_test.go
  controllers/config/defaults.go
  controllers/dspastatus/dspa_status.go
  controllers/dspipeline_controller.go
  controllers/dspipeline_params.go
  controllers/metrics.go
  controllers/mlmd.go
  controllers/mlmd_test.go
  controllers/util/util.go
  tests/resources/dspa-external-lite.yaml
  tests/resources/dspa-lite.yaml
  tests/suite_test.go
  tests/util/resources.go
Labels: approved, lgtm

#685 add newlines between certs
  controllers/dspipeline_params.go
  controllers/testdata/declarative/case_6/deploy/00_configmap.yaml
  controllers/testdata/declarative/case_6/expected/created/configmap_dspa_trusted_ca.yaml
  controllers/testdata/declarative/case_8/expected/created/configmap_dspa_trusted_ca.yaml
  controllers/testutil/equalities.go
Labels: lgtm

#686 Added MLMD GRPC Server Network Policy
  config/internal/ml-metadata/metadata-grpc.networkpolicy.yaml.tmpl
Labels: approved, lgtm

#688 make mlmd grpc NP more permissive
  config/internal/ml-metadata/metadata-grpc.networkpolicy.yaml.tmpl
Labels: lgtm

#687 fix default envoy route behavior
  controllers/dspipeline_params.go
  tests/resources/dspa-external-lite.yaml
  tests/resources/dspa-lite.yaml
Labels: approved, lgtm

#689 update compatibility doc for 2.5
  docs/release/compatibility.md
  docs/release/compatibility.yaml
Labels: approved, lgtm

#691 add kuberoot-ca to sample
  config/samples/v2/dspa-simple/dspa_simple.yaml
Labels: approved, lgtm

#690 Release v2.5.0
  config/base/params.env
Labels: approved, lgtm, release-automation

#695 chore: Improved logs for tests
  controllers/testutil/util.go
Labels: approved, lgtm
