Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2024-07, with the labels that each got.

#668 Enabled sample pipeline in DSPA samples
  config/samples/v1/custom-configs/dspa.yaml
  config/samples/v1/dspa-all-fields/dspa_all_fields.yaml
  config/samples/v1/dspa-local-dev/dspa_local_dev.yaml
  config/samples/v1/dspa-simple/dspa_simple.yaml
  config/samples/v1/external-object-storage/dspa.yaml
  config/samples/v2/custom-configs/dspa.yaml
  config/samples/v2/custom-workflow-controller-config/dspa.yaml
  config/samples/v2/dspa-all-fields/dspa_all_fields.yaml
  config/samples/v2/dspa-simple/dspa_simple.yaml
  config/samples/v2/external-object-storage/dspa.yaml
  config/samples/v2/local-dev/dspa.yaml
Labels: approved, lgtm

#671 increase integration db resources
  .github/resources/dspa-lite/dspa.yaml
  .github/resources/mariadb/deployment.yaml
  tests/resources/dspa-lite.yaml
Labels: lgtm

#670 feat: add the ability to configure artifact download link expiry
  api/v1alpha1/dspipeline_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  config/internal/apiserver/default/role_ds-pipeline.yaml.tmpl
  config/samples/v2/dspa-simple/dspa_simple.yaml
  controllers/config/defaults.go
  controllers/dspipeline_params.go
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_6/deploy/03_cr.yaml
  controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_7/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_8/expected/created/apiserver_deployment.yaml
Labels: approved, lgtm

#673 Release v2.4.0
  config/base/params.env
Labels: release-automation

#674 Move embedded binary and bash calls from YAML to a single script
  .github/scripts/tests/kind-integration.sh
  .github/workflows/kind-integration.yml
Labels: approved, lgtm

#676 increase default expiry for signed url
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  controllers/config/defaults.go
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_7/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_8/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_9/expected/created/apiserver_deployment.yaml
Labels: approved, lgtm
