Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2024-05, with the labels that each got.

#636 Added CustomConfig to WorkflowController
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/workflow-controller/deployment.yaml.tmpl
  config/samples/v2/custom-workflow-controller-config/custom-workflow-controller-configmap.yaml
  config/samples/v2/custom-workflow-controller-config/dspa.yaml
  config/samples/v2/custom-workflow-controller-config/kustomization.yaml
Labels: lgtm

#628 Replaced Ginkgo and Gomega with Testify in functional tests
  controllers/dspipeline_controller_func_test.go
  controllers/suite_test.go
  controllers/testutil/util.go
  go.mod
  go.sum
Labels: lgtm

#635 Update integration tests to use TLS enabled DB/storage
  .github/resources/mariadb/certs-secret.yaml
  .github/resources/mariadb/deployment.yaml
  .github/resources/mariadb/kustomization.yaml
  .github/resources/mariadb/self-signed-ca-configmap.yaml
  .github/resources/mariadb/tls-config-configmap.yaml
  .github/resources/minio/cabundle-configmap.yaml
  .github/resources/minio/certs-secret.yaml
  .github/resources/minio/deployment.yaml
  .github/resources/minio/kustomization.yaml
  .github/resources/tls/root-ca-configmap.yaml
  .github/workflows/kind-integration.yml
  .gitleaks.toml
  tests/resources/dspa-external-lite.yaml
Labels: approved, lgtm

#638 Added new Network Policy to access Mariadb from DSPO
  config/internal/common/default/mariadb-access-policy.yaml.tmpl
  config/manager/manager.yaml
  controllers/dspipeline_params.go
Labels: approved, lgtm

#641 chore: refactor params.env
  config/base/kustomization.yaml
  config/base/params.env
  config/manager/manager.yaml
Labels: lgtm

#647 chore: deploy mariadb nwp with mariadb
  config/internal/mariadb/default/networkpolicy.yaml.tmpl
  controllers/database.go
Labels: lgtm

#648 Release v2.2.0
  config/base/params.env
Labels: approved, lgtm, release-automation

#650 Updated metadata envoy route name
  config/internal/ml-metadata/metadata-envoy.route.yaml.tmpl
  config/internal/ml-metadata/metadata-envoy.service.yaml.tmpl
Labels: approved, lgtm

#652 RHOAIENG-7423 - Updated ubi8 image
  Dockerfile
Labels: approved, lgtm

#653 FIX - Update metadata envoy service name in mlpipelines-ui deployment file
  config/internal/ml-metadata/metadata-envoy.serviceaccount.yaml.tmpl
  config/internal/mlpipelines-ui/deployment.yaml.tmpl
  controllers/testdata/declarative/case_2/expected/created/mlpipelines-ui_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/mlpipelines-ui_deployment.yaml
  controllers/testdata/declarative/case_5/expected/created/mlpipelines-ui_deployment.yaml
  controllers/testdata/declarative/case_7/expected/created/mlpipelines-ui_deployment.yaml
Labels: approved, lgtm

#639 Added option to enable/disable envoy route
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/ml-metadata/route/metadata-envoy.route.yaml.tmpl
  controllers/dspipeline_params.go
  controllers/mlmd.go
  controllers/mlmd_test.go
Labels: approved, lgtm, do-not-merge/hold

#655 Fixed typo
  tests/pipeline_runs_test.go
Labels: approved, lgtm

#651 Fixed the DSPA status update on reconciliation
  controllers/apiserver_test.go
  controllers/dspastatus/dspa_status.go
  controllers/dspipeline_controller.go
  controllers/persistence_agent_test.go
  controllers/scheduled_workflow_test.go
  controllers/workflow_controller.go
Labels: approved, lgtm

#654 Added routes permissions to pipeline runner
  config/internal/apiserver/default/role_pipeline-runner.yaml.tmpl
Labels: approved, lgtm
