Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2025-03, with the labels that each got.

#797 Pin the KFP version in the custom PyPi integration test
  .github/scripts/python_package_upload/package_download.sh
  .github/workflows/kind-integration.yml
Labels: approved, lgtm

#799 Sync main into stable
  .github/resources/mariadb/deployment.yaml
  .github/scripts/python_package_upload/package_download.sh
  .github/workflows/kind-integration.yml
  .github/workflows/precommit.yml
  config/base/params.env
  config/component_metadata.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  config/internal/scheduled-workflow/deployment.yaml.tmpl
  config/manager/manager.yaml
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
Labels: lgtm

#800 Replace the generic runtime image in the InstructLab pipeline
  config/internal/apiserver/default/deployment.yaml.tmpl
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
Labels: approved, lgtm

#803 update compatibility doc for 2.11
  docs/release/compatibility.md
  docs/release/compatibility.yaml
Labels: approved

#806 Merge 2.11.0 to stable
  Makefile
  api/v1/dspipeline_types.go
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/base/params.env
  config/configmaps/files/config.yaml
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  config/rbac/role.yaml
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
  docs/release/compatibility.md
  docs/release/compatibility.yaml
Labels: approved, lgtm
