Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2025-02, with the labels that each got.

#778 update upload-artifact in gh ci
  .github/workflows/build-prs-trigger.yaml
  .github/workflows/build-prs.yml
  .github/workflows/release_create.yaml
  .github/workflows/release_trigger.yaml
Labels: approved, lgtm

#777 add runtime image
  .github/scripts/release_prep/create_branches.sh
  .github/scripts/release_prep/prereqs.sh
  .github/workflows/build-tags.yml
  .github/workflows/release_prep.yaml
  api/v1/dspipeline_types.go
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/dspipeline_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/base/kustomization.yaml
  config/base/params.env
  config/configmaps/files/config.yaml
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  config/manager/manager.yaml
  controllers/config/defaults.go
  controllers/dspipeline_params.go
  controllers/testdata/declarative/case_0/config.yaml
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_1/config.yaml
  controllers/testdata/declarative/case_2/config.yaml
  controllers/testdata/declarative/case_2/deploy/cr.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/config.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/config.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/config.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_6/config.yaml
  controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
  controllers/testutil/equalities.go
  docs/release/compatibility.md
  docs/release/compatibility.yaml
  scripts/release/params.py
  tests/resources/dspa-external-lite.yaml
  tests/resources/dspa-external.yaml
Labels: lgtm

#780 fix: glog upgraded to 1.2.4 fixes CVE GO-2025-3372
  go.mod
  go.sum
Labels: approved, lgtm

#781 Dynamically Update SampleConfig JSON
  api/v1/dspipeline_types.go
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/dspipeline_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/base/kustomization.yaml
  config/base/params.env
  config/configmaps/files/config.yaml
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  config/internal/apiserver/sample-pipeline/sample-config.yaml.tmpl
  config/manager/manager.yaml
  config/overlays/make-deploy/kustomization.yaml
  controllers/apiserver.go
  controllers/config/defaults.go
  controllers/dspipeline_controller.go
  controllers/dspipeline_params.go
  controllers/testdata/declarative/case_0/config.yaml
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_1/config.yaml
  controllers/testdata/declarative/case_2/config.yaml
  controllers/testdata/declarative/case_2/deploy/cr.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/sample-config.yaml.tmpl
  controllers/testdata/declarative/case_3/config.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/config.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/config.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_6/config.yaml
  controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
Labels: lgtm

#783 update compatibility doc for 2.11
  docs/release/compatibility.md
  docs/release/compatibility.yaml
Labels: approved, lgtm

#784 Revert "update compatibility doc for 2.11"
  docs/release/compatibility.md
  docs/release/compatibility.yaml
Labels: approved, lgtm

#785 Revert make-deploy overlay to use ODH:main image
  config/overlays/make-deploy/kustomization.yaml
Labels: lgtm

#788 update params to match latest configs
  scripts/release/params.py
Labels: lgtm

#787 Release v2.10.0
  config/base/params.env
  scripts/release/params.py
Labels: approved, release-automation

#789 correct dspo platformversion
  config/manager/manager.yaml
Labels: lgtm

#786 Provide APIServer init and main Containers with same envs
  config/internal/apiserver/default/deployment.yaml.tmpl
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
Labels: approved, lgtm

#791 fix: Update InstructLab pipeline filepath reference
  config/configmaps/files/config.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
Labels: approved, lgtm

#793 fix: Update InstructLab pipeline filepath reference
  config/configmaps/files/config.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  controllers/testdata/declarative/case_0/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_2/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_3/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_4/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_5/expected/created/apiserver_deployment.yaml
  controllers/testdata/declarative/case_6/expected/created/apiserver_deployment.yaml
Labels: approved, lgtm

#794 Upgraded actions/cache to v4
  .github/workflows/precommit.yml
Labels: approved, lgtm
