Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2025-01, with the labels that each got.

#764 Add ilab kfp pipeline to the DSPO repo
  api/v1/dspipeline_types.go
  api/v1alpha1/dspipeline_types.go
  config/crd/bases/datasciencepipelinesapplications.opendatahub.io_datasciencepipelinesapplications.yaml
  config/internal/apiserver/default/deployment.yaml.tmpl
  config/internal/apiserver/sample-pipeline/sample-config.yaml.tmpl
  controllers/apiserver.go
  controllers/dspipeline_params.go
  tests/pipeline_test.go
  tests/resources/dspa-lite.yaml
  tests/resources/test-pipeline-run.yaml
  tests/resources/test-pipeline-with-custom-pip-server-run.yaml
  tests/util/rest.go
Labels: approved, lgtm

#770 Address CVE-2024-45338
  go.mod
  go.sum
Labels: lgtm

#773 update compatibility doc for 2.9
  docs/release/compatibility.md
  docs/release/compatibility.yaml
Labels: lgtm

#775 update mariadb/oauthproxy/envoy
  config/base/params.env
Labels: lgtm

#774 Release v2.9.0
  config/base/params.env
Labels: approved, lgtm, release-automation

#776 merge v2.9.0 to stable
  .github/actions/kind/action.yml
  .github/scripts/python_package_upload/Dockerfile
  .github/scripts/python_package_upload/package_download.sh
  .github/scripts/tests/README.md
  .github/scripts/tests/collect_logs.sh
  .github/scripts/tests/tests.sh
  .github/workflows/kind-integration.yml
  OWNERS
  README.md
  config/base/params.env
  config/component_metadata.yaml
  controllers/database.go
  docs/release/RELEASE.md
  docs/release/compatibility.md
  docs/release/compatibility.yaml
  go.mod
  go.sum
  scripts/release/params.py
  tests/resources/dspa-external.yaml
  tests/resources/dspa.yaml
  tests/resources/test-pipeline-run.yaml
  tests/resources/test-pipeline-with-custom-pip-server-run.yaml
Labels: lgtm
