Repository opendatahub-io/data-science-pipelines-operator, pull requests merged in 2025-04, with the labels that each got.

#807 fix ordering of params.env images
  config/base/params.env
Labels: approved, lgtm

#812 replace iris data set with working link
  config/internal/apiserver/sample-pipeline/sample-pipeline.yaml.tmpl
Labels: lgtm

#813 Fix run submissions with OwnerReferencesPermissionEnforcement on
  config/internal/apiserver/default/role_ds-pipeline.yaml.tmpl
Labels: approved, lgtm

#815 Release v2.12.0
  config/base/params.env
Labels: approved, lgtm, release-automation
